### ISSUE TITLE
how to run 

### ISSUE THREAD

**Issue by 13293824182** [agethen/RPAN#1]
How can I use your code to classify videos?

**Comment by l2009312042** [comment]
yes ,lack of tutorial   to use this code

**Comment by l2009312042** [comment]
in data_handle.py ,this line  is is error  :label[b-start, :] = class_dict[action[0]]

**Comment by agethen** [comment]
Sorry about that; the uploaded version is not complete, I will upload a fixed version later today. Thank you!

**Comment by agethen** [comment]
I have uploaded a minimal example run.py, which you need to edit accordingly. 
You may likely want to add some functionality as well, such as printing results etc (I may add this at a later stage).
If there are any further questions, feel free to ask.

**Comment by l2009312042** [comment]
thx  but i have another question , when load resnet_v2.py,it fails, and report as follow:
Util.py: Loading from resnet_v2.npy
NOT loading weights, as file resnet_v2.npy was not found. Please edit util.py.
Continuing with random weights.
is this file is ok?  
looking forward to your reply

**Comment by l2009312042** [comment]
thx but i have another question , when load resnet_v2.py,it fails, and report as follow:
Util.py: Loading from resnet_v2.npy
NOT loading weights, as file resnet_v2.npy was not found. Please edit util.py.
Continuing with random weights.
is this file is ok?
looking forward to your reply

**Comment by l2009312042** [comment]
thx but i have another question , when load resnet_v2.npy,it fails, and report as follow:
Util.py: Loading from resnet_v2.npy
NOT loading weights, as file resnet_v2.npy was not found. Please edit util.py.
Continuing with random weights.
is this file is ok?
looking forward to your reply

**Comment by agethen** [comment]
Hi,
Please make sure the path in line 4 in util.py is correct. Try an absolute path if it did not work so-far. 
If you start out with random weights you will have a hard time (and the ResNet Batch Normalization layers are not setup for learning right now).

**Comment by l2009312042** [comment]
thx for your reply .an absolute path  is not work , i think  the file maybe has some wrong 
the file video1.npy  is ok

**Comment by agethen** [comment]
Hm, well it's not impossible I suppose, but seems unlikely?
Check out if the md5sum is correct, and download the file again if not:
```
md5sum resnet_v2.npy 
506d0bf5c1cc4fd19b385646153cf2c7  resnet_v2.npy
```
