### ISSUE TITLE
about the implementation result

### ISSUE THREAD

**Issue by demianzhang** [agethen/RPAN#2]
Could you tell me the finally result comparing with the original paper. Many thanks.

**Comment by agethen** [comment]
Hi,

I did run it on JHMDB (RGB, split 1), where I got 61.3% Top-1 accuracy. The paper got 60.0, but I think the authors did not use ResNet as a base.
For comparison, I got 59.3% for a ResNet + LSTM + Classifier baseline.

**Comment by demianzhang** [comment]
Thanks for your reply.
